# Neden NumPy?

In [4]:
a = [1,2,3,4]
b = [2,3,4,5]
a
b   # son islemi yazdirir

[2, 3, 4, 5]

In [5]:
a

[1, 2, 3, 4]

In [6]:
ab = []
for i in range(0,len(a)):
    ab.append(a[i]*b[i])
    
ab    

[2, 6, 12, 20]

In [2]:
import numpy as np

In [8]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [9]:
a*b

array([ 2,  6, 12, 20])

In [10]:
import numpy as np

In [11]:
a = np.array([1,2,34,4])

array([ 1,  2, 34,  4])

In [12]:
type(a)

numpy.ndarray

In [13]:
np.array([3.14,4,2,13]) #tek tip veri tuttugu icin sayilarin hepsini float da cevirdi

array([ 3.14,  4.  ,  2.  , 13.  ])

In [14]:
np.array([3.14,4,2,13], dtype = 'int') # ondalikli sayi olmasina ragmen int olarak tuttu 3.14 u 3 yuvarladi

array([ 3,  4,  2, 13])

In [15]:
# sifirdan array olusturmak

In [16]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones((3,5) , dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.full((3,5),3, dtype='int')

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [96]:
np.arange(0,10)  # arange fonksiyonun bastaki dahil sondaki dahil degil

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.arange(0,33,3) 

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [20]:
np.linspace(0,1,10)  # o dan 1 e kadar 10 tane sayi 

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [24]:
np.random.normal(10,4,(3,4)) birinci ortalama ikinci standart sapma

array([[14.35600217,  7.29280633, 16.82029096, 11.7344562 ],
       [11.64557731,  7.99297953,  3.288528  ,  7.73907909],
       [15.68385758,  2.21396144, 11.38769571, 10.71020798]])

In [25]:
np.random.randint(0,10,(3,3))

array([[0, 8, 9],
       [7, 2, 9],
       [6, 8, 9]])

In [26]:
#numpy array ozellikler

## ozellikler
# . **ndim**:boyut sayisi
# . **shape**: boyut bilgisi
# . **size**: toplam eleman sayisi
# . **dtype**: array veri tipi

In [27]:
import numpy as np

In [5]:
a = np.random.randint(0,10,size=112)

In [6]:
a

array([4, 2, 9, 8, 8, 3, 0, 7, 3, 5, 6, 4, 0, 1, 7, 5, 0, 7, 5, 4, 8, 3,
       0, 7, 5, 5, 1, 3, 8, 4, 3, 4, 9, 2, 5, 5, 5, 7, 9, 2, 4, 7, 4, 5,
       9, 4, 3, 8, 5, 1, 4, 6, 2, 3, 9, 8, 0, 2, 0, 8, 4, 6, 2, 6, 6, 5,
       8, 5, 8, 1, 4, 1, 5, 7, 5, 0, 0, 7, 2, 1, 2, 0, 7, 8, 2, 5, 4, 3,
       7, 7, 9, 2, 8, 2, 8, 2, 4, 1, 4, 0, 4, 0, 8, 2, 8, 2, 2, 2, 1, 7,
       8, 2])

In [30]:
a.ndim


1

In [33]:
a.shape

(10,)

In [34]:
a.size

10

In [35]:
a.dtype

dtype('int32')

In [36]:
b=np.random.randint(10, size=(3,5))

In [37]:
b

array([[4, 5, 5, 3, 4],
       [5, 9, 4, 3, 3],
       [8, 0, 0, 2, 5]])

In [38]:
b.ndim

2

In [39]:
b.shape

(3, 5)

In [40]:
b.size

15

In [41]:
b.dtype

dtype('int32')

### Yeniden Sekillendirme (reshaping)

In [42]:
import numpy as np 

In [43]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a = np.arange(1,10)
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
a=np.arange(1,10)  # 1 boyutlu array
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
b=a.reshape((1,9)) #2 boyutlu array
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [49]:
b.ndim

2

### Array Birlestirme (Concatenation)

In [50]:
import numpy as np

In [51]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [52]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
z = np.array([8,9,10,11])

In [54]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10, 11])

In [55]:
# iki boyut

In [56]:
a = np.array([[1,2,3],
              [1,2,3]])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [57]:
np.concatenate([a,a]) # satir bazinda birlesme olur

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [58]:
np.concatenate([a,a], axis=0)   # satir bazinda birlesme olur

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [60]:
np.concatenate([a,a], axis=1) # yan yana yazar yani sutun bazinda birlestirme

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

### Array Ayirma (Splitting)

In [61]:
import numpy as np

In [62]:
x = np.array([1,2,3,99,99,3,2,1])

In [63]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [64]:
a,b,c = np.split(x,[3,5])

In [65]:
a

array([1, 2, 3])

In [66]:
b

array([99, 99])

In [67]:
c

array([3, 2, 1])

In [68]:
# iki boyutlu ayirma

In [69]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [71]:
ust,alt = np.vsplit(m,[2])

In [72]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [73]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [76]:
sag,sol = np.hsplit(m,[2])

In [79]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [80]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

### Array Siralama (Sorting

In [81]:
import numpy as np

In [82]:
v =np.array([2,1,4,3,5])

In [84]:
v

array([2, 1, 4, 3, 5])

In [85]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [86]:
m = np.random.normal(20,5,(3,3))
m

array([[31.25498934, 29.29106235, 23.34952859],
       [16.40245948, 15.80458091,  8.76348922],
       [16.05526625, 19.94357994, 19.23369854]])

In [87]:
np.sort(m) # satira gore siraladi

array([[23.34952859, 29.29106235, 31.25498934],
       [ 8.76348922, 15.80458091, 16.40245948],
       [16.05526625, 19.23369854, 19.94357994]])

In [88]:
np.sort(m, axis=0) # sutuna gore siraladi

array([[16.05526625, 15.80458091,  8.76348922],
       [16.40245948, 19.94357994, 19.23369854],
       [31.25498934, 29.29106235, 23.34952859]])

In [89]:
np.sort(m, axis=1)   # satira gore siraladi

array([[23.34952859, 29.29106235, 31.25498934],
       [ 8.76348922, 15.80458091, 16.40245948],
       [16.05526625, 19.23369854, 19.94357994]])

### Quiz 15

In [90]:
#Aşağıdaki kodun çıktısı hangisidir?

import numpy as np
np.array([3.14, 4,6,1.2])

array([3.14, 4.  , 6.  , 1.2 ])

### Quiz 17

In [92]:
#Aşağıda verilen çıktının kodu hangisidir?

a=np.array([[[7, 9],

[4, 0],

[5, 9]],



[[4, 8],

[6, 4],

[4, 5]],



[[2, 2],

[8, 2],

[0, 2]]])

array([[[7, 9],
        [4, 0],
        [5, 9]],

       [[4, 8],
        [6, 4],
        [4, 5]],

       [[2, 2],
        [8, 2],
        [0, 2]]])

In [93]:
np.random.randint(10, size=(3,3,2))

array([[[5, 4],
        [8, 0],
        [9, 5]],

       [[1, 7],
        [0, 7],
        [8, 6]],

       [[0, 5],
        [2, 9],
        [3, 0]]])

In [94]:
np.arange(0,10)  # arange fonksiyonunda bastaki dahil sondaki dahil degil

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
#Aşağıdaki kodun çıktısı nedir?

5*np.array([1, 2,3])  

array([ 5, 10, 15])

# Index Elemanlarina Ulasmak

In [98]:
import numpy as np
a = np.random.randint(10, size =10)
a

array([3, 2, 1, 7, 8, 7, 4, 6, 5, 4])

In [99]:
a[0]

3

In [100]:
a[-1] # tersden sayar

4

In [101]:
a[0]=100 # a arrayini o inci indexdeki elemanin degirti 

In [102]:
a

array([100,   2,   1,   7,   8,   7,   4,   6,   5,   4])

In [103]:
import numpy as np
m= np.random.randint(10, size =(3,5))
m

array([[0, 4, 0, 6, 4],
       [8, 6, 6, 4, 2],
       [4, 6, 0, 4, 2]])

In [104]:
m[0,0]

0

In [105]:
m[2,3]

4

In [106]:
m[1,4]=99 # elemanin degistirdi

In [107]:
m

array([[ 0,  4,  0,  6,  4],
       [ 8,  6,  6,  4, 99],
       [ 4,  6,  0,  4,  2]])

In [108]:
m[1,4]=2.2   # basda bir tane float degerr olsaydi hepsini float olarak ayarlayacakti ama sonradan degistirip 
                #bir float deger atarsak float degeri int cevirir cunku ilk bastaki yaoiyi bozmak istemez 
m

array([[0, 4, 0, 6, 4],
       [8, 6, 6, 4, 2],
       [4, 6, 0, 4, 2]])

# Array Alt Kumesine Erismek (Slicing)

In [109]:
import numpy as np

In [110]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [111]:
a[0:3]

array([20, 21, 22])

In [112]:
a[:3]

array([20, 21, 22])

In [113]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [114]:
a[1::2]

array([21, 23, 25, 27, 29])

In [115]:
a[2::3]

array([22, 25, 28])

In [116]:
a[0::3]

array([20, 23, 26, 29])

In [117]:
# iki boyutlu slice islemleri

In [118]:
import numpy as np
m = np.random.randint(10, size=(5,5))
m

array([[3, 6, 0, 6, 2],
       [6, 7, 1, 0, 6],
       [8, 2, 8, 9, 5],
       [3, 6, 7, 0, 8],
       [3, 4, 7, 3, 7]])

In [119]:
m[:,0]

array([3, 6, 8, 3, 3])

In [120]:
m[:,4]

array([2, 6, 5, 8, 7])

In [121]:
m[0,:]

array([3, 6, 0, 6, 2])

In [122]:
m[3,:]

array([3, 6, 7, 0, 8])

In [123]:
m[0:2,0:3]

array([[3, 6, 0],
       [6, 7, 1]])

In [124]:
 m[:,:2]

array([[3, 6],
       [6, 7],
       [8, 2],
       [3, 6],
       [3, 4]])

In [125]:
m[1:3,0:2]

array([[6, 7],
       [8, 2]])

### Alt Kume Uzerinde Islem Yapmak

In [126]:
import numpy as np
a = np.random.randint(10,size=(5,5))
a

array([[1, 1, 8, 7, 9],
       [7, 4, 9, 0, 8],
       [0, 7, 3, 7, 2],
       [6, 9, 2, 7, 5],
       [4, 0, 4, 1, 6]])

In [127]:
alt_a= a[0:3,0:2]
alt_a

array([[1, 1],
       [7, 4],
       [0, 7]])

In [128]:
alt_a[0,0]=9999
alt_a[1,1]=888
alt_a

array([[9999,    1],
       [   7,  888],
       [   0,    7]])

In [130]:
a    # alt kumede yapilan degisiklik kumenin tamamimnda da degisiklige yol aciyor

array([[9999,    1,    8,    7,    9],
       [   7,  888,    9,    0,    8],
       [   0,    7,    3,    7,    2],
       [   6,    9,    2,    7,    5],
       [   4,    0,    4,    1,    6]])

In [131]:
m = np.random.randint(10,size=(5,5))
m


array([[9, 6, 0, 4, 6],
       [0, 0, 3, 1, 4],
       [0, 4, 1, 9, 3],
       [8, 3, 5, 0, 2],
       [3, 2, 9, 8, 6]])

In [132]:
alt_b=m[0:3,0:2].copy()  # copy metodunu kullanarak sadece alt kume uzerinde islem yapabiliriz
alt_b

array([[9, 6],
       [0, 0],
       [0, 4]])

In [134]:
alt_b[0,0]=999
alt_b[1,1]=888
alt_b

array([[999,   6],
       [  0, 888],
       [  0,   4]])

In [135]:
m   # m arrainde herhangi bir degisiklik olmadi

array([[9, 6, 0, 4, 6],
       [0, 0, 3, 1, 4],
       [0, 4, 1, 9, 3],
       [8, 3, 5, 0, 2],
       [3, 2, 9, 8, 6]])

###  Fancy Index ile Elemanlara Erismek

In [136]:
import numpy as np
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [137]:
v[1]

3

In [138]:
v[3]

9

In [140]:
[v[1],v[3],v[5]]  # indexleri tek tek bir listeye atarsak 

[3, 9, 15]

In [141]:
al_getir = [1,3,5,]
v[al_getir]

array([ 3,  9, 15])

In [142]:
# iki boyutlu fancy

In [143]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [144]:
satir = np.array([0,1])
sutun = np.array([1,2])
m[satir,sutun]

array([1, 5])

In [145]:
# basit index ile fancy index

In [146]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [148]:
m[0,[1,2]]  #index ile fancy

array([1, 2])

In [149]:
m[0: ,[1,2]] # slice ile fancy

array([[1, 2],
       [4, 5],
       [7, 8]])

In [150]:
m[0: ,1:]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Kosullu Eleman Islemleri

In [151]:
import numpy as np
v = np.array([1,2,3,4,5])



In [152]:
v>5

array([False, False, False, False, False])

In [153]:
v<3

array([ True,  True, False, False, False])

In [154]:
v[v>3]

array([4, 5])

In [162]:
v[v==3]  # arka tarafda fancy calisir

array([3])

In [156]:
v[v!=3]

array([1, 2, 4, 5])

In [157]:
v+2

array([3, 4, 5, 6, 7])

In [158]:
v*2

array([ 2,  4,  6,  8, 10])

In [159]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [160]:
v*55/10

array([ 5.5, 11. , 16.5, 22. , 27.5])

In [161]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

### MAtematiksel Islemler

In [163]:
import numpy as np
v = np.array([1,2,3,4,5])

In [164]:
v-1

array([0, 1, 2, 3, 4])

In [165]:
v*5

array([ 5, 10, 15, 20, 25])

In [166]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [167]:
v*5/10-1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [168]:
# ufunc 

In [169]:
np.subtract(v,1) #v-1

array([0, 1, 2, 3, 4])

In [170]:
np.add(v,3) 

array([4, 5, 6, 7, 8])

In [171]:
np.multiply(v,4) # v*4

array([ 4,  8, 12, 16, 20])

In [172]:
np.divide(v,3) # v/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [173]:
np.power(v,3) #v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [175]:
np.mod(v,2) # v%2

array([1, 0, 1, 0, 1], dtype=int32)

In [176]:
np.absolute(np.array([8-3]))

array([5])

In [177]:
np.sin(360)

0.9589157234143065

In [178]:
np.cos(180)

-0.5984600690578582

In [179]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [180]:
np.log2(v)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [181]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Dell\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\dell\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

In [182]:
#cheatsheet 


### Numpy iile Iki Bilinmeyenli Denklem Cozumu


In [183]:
import numpy as np


# 5*x0+x1=12
# x0+3*x1=10

In [184]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [185]:
a

array([[5, 1],
       [1, 3]])

In [186]:
b

array([12, 10])

In [189]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

## Quiz 19,20,21

In [190]:
a = np.array([[4, 7, 4, 5, 9],

            [2, 5, 0, 7, 7],

            [1, 9, 0, 8, 2]])

a[:2,:3]

array([[4, 7, 4],
       [2, 5, 0]])

In [191]:
m =np.array([[0, 1, 2],

             [3, 4, 5],

             [6, 7, 8]])



m[0, [1,2]]

array([1, 2])

In [192]:
m = np.array([[0, 1, 2],

             [3, 4, 5],

             [6, 7, 8]])



m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])